/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/aspnet-3d.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.NurbsPath.geometry} material={materials['Material.002']} scale={[2.7, 3.1, 3.1]} />
    </group>
  )
}

useGLTF.preload('/aspnet-3d.glb')
