/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/css-3d.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials.SVGMat} scale={13.41} />
    </group>
  )
}

useGLTF.preload('/css-3d.glb')
