/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { useThree } from "@react-three/fiber";

export default function Model({scale}) {

  const group = useRef();
  const { nodes, materials } = useGLTF('/models/mongo-3d.glb');

  useThree(({camera}) => {
    camera.position.y = 80;
    camera.lookAt(0, 0, 0);
  });

  return (
    <group ref={group} dispose={null}>
      <group scale={7}>
        <mesh geometry={nodes.Curve001_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Curve001_2.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/mongo-3d.glb');
