/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/node-3d.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials['SVGMat.002']}
        position={[0.02, 0.1, 0]}
        rotation={[-0.01, 0, 0]}
        scale={13.7}
      />
    </group>
  )
}

useGLTF.preload('/node-3d.glb')
