/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/react-3d.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.001']} scale={1.12} />
      <mesh geometry={nodes.Curve001.geometry} material={materials.SVGMat} />
    </group>
  )
}

useGLTF.preload('/react-3d.glb')
