/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/sphere-txt.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log(actions)
    actions["TextAction.001"].play();
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials.SVGMat}
        position={[1.22, 0.84, 2.06]}
        rotation={[1.07, -0.21, -0.51]}
        scale={[2, 1.51, 2]}
      />
      <mesh
        geometry={nodes.NurbsPath.geometry}
        material={nodes.NurbsPath.material}
        position={[-1.13, 1.89, 1.27]}
        rotation={[0.55, 0.09, 0.46]}
        scale={[0.45, 0.37, 0.45]}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={nodes.Circle.material}
        position={[1.15, 2.22, 0.49]}
        rotation={[0.21, -0.03, -0.48]}
        scale={[0.7, 0.56, 0.7]}
      />
      <mesh
        geometry={nodes.Curve001.geometry}
        material={nodes.Curve001.material}
        position={[-0.07, 2.29, -1.12]}
        rotation={[-0.46, -0.03, 0.02]}
        scale={[2, 1.56, 2]}
      />
      <mesh
        geometry={nodes.Curve002.geometry}
        material={nodes.Curve002.material}
        position={[-0.49, 0.14, 2.49]}
        rotation={[-1.58, 0.24, 2.95]}
        scale={[2, 1.34, 2]}
      />
      <group position={[2.48, 0, 0.54]} rotation={[-0.35, -0.2, -1.64]} scale={[8.5, 7.6, 8.5]}>
        <mesh geometry={nodes.Curve004_1.geometry} material={nodes.Curve004_1.material} />
        <mesh geometry={nodes.Curve004_2.geometry} material={nodes.Curve004_2.material} />
      </group>
      <group position={[-1.82, 1.65, -0.64]} rotation={[-0.25, -0.12, 0.81]} scale={[0.15, 0.17, 0.17]}>
        <mesh geometry={nodes.Plane002_1.geometry} material={nodes.Plane002_1.material} />
        <mesh geometry={nodes.Plane002_2.geometry} material={nodes.Plane002_2.material} />
      </group>
      <mesh
        geometry={nodes.Curve004.geometry}
        material={nodes.Curve004.material}
        position={[1.81, 1.32, -1.2]}
        rotation={[-0.47, 0.26, -0.83]}
        scale={[2.2, 1.71, 2.2]}
      />
      <mesh
        geometry={nodes.Circle001.geometry}
        material={nodes.Circle001.material}
        position={[-0.27, 0.55, -2.46]}
        rotation={[-1.35, -0.06, 0.1]}
        scale={[0.18, 0.11, 0.18]}
      />
      <mesh
        geometry={nodes.Curve005.geometry}
        material={materials['SVGMat.005']}
        position={[-0.16, 1.94, -1.65]}
        rotation={[-0.71, -0.02, 0.06]}
        scale={0.1}
      />
      <group name="Cube003" rotation={[-1.07, 0.09, 1.75]} scale={[0.08, 0.22, 0.6]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.010']} />
      </group>
      <mesh
        geometry={nodes.Circle002.geometry}
        material={nodes.Circle002.material}
        position={[-1.18, -2.11, -0.79]}
        rotation={[-0.91, -1.07, 1.83]}
        scale={[0.7, 0.56, 0.7]}
      />
      <mesh
        geometry={nodes.Circle003.geometry}
        material={nodes.Circle003.material}
        position={[1.06, -1.5, 1.76]}
        rotation={[2.5, 0.44, -0.48]}
        scale={[0.18, 0.11, 0.18]}
      />
      <group position={[1.71, -1.89, 0.02]} rotation={[0.92, -0.71, -2.03]} scale={[0.15, 0.17, 0.17]}>
        <mesh geometry={nodes.Plane001_1.geometry} material={nodes.Plane001_1.material} />
        <mesh geometry={nodes.Plane001_2.geometry} material={nodes.Plane001_2.material} />
      </group>
      <mesh
        geometry={nodes.Curve006.geometry}
        material={nodes.Curve006.material}
        position={[1.67, -0.6, -1.81]}
        rotation={[-3.14, -0.83, -1.33]}
        scale={[2, 1.34, 2]}
      />
      <group position={[-2.05, -0.51, -1.4]} rotation={[2.94, 0.62, 1.48]} scale={[8.5, 7.6, 8.5]}>
        <mesh geometry={nodes.Curve008_1.geometry} material={nodes.Curve008_1.material} />
        <mesh geometry={nodes.Curve008_2.geometry} material={nodes.Curve008_2.material} />
      </group>
      <mesh
        geometry={nodes.Curve008.geometry}
        material={nodes.Curve008.material}
        position={[-1.08, -1.96, 1.2]}
        rotation={[-0.09, 0.76, 2.51]}
        scale={[2, 1.56, 2]}
      />
      <mesh
        geometry={nodes.Curve009.geometry}
        material={nodes.Curve009.material}
        position={[-2.4, -0.2, 0.8]}
        rotation={[0.6, 0.32, 1.46]}
        scale={[2.2, 1.71, 2.2]}
      />
      <mesh
        geometry={nodes.NurbsPath001.geometry}
        material={nodes.NurbsPath001.material}
        position={[0.46, -1.81, -1.73]}
        rotation={[-2.08, 1, -0.35]}
        scale={[0.4, 0.33, 0.4]}
      />
      <mesh
        name="Text"
        geometry={nodes.Text.geometry}
        material={materials['Material.011']}
        position={[-0.12, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} scale={-2.57} />
    </group>
  )
}

useGLTF.preload('/models/sphere-txt.glb')
