/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/sql-3d.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Cube003" rotation={[0, Math.PI / 2, 0]} scale={[0.41, 1.93, 3.38]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/sql-3d.glb')
